LOCATION_COLS = [
    "Ballsbridge",
    "Blackrock",
    "Booterstown",
    "Bray",
    "Cabinteely",
    "Clonskeagh",
    "Clontarf",
    "City Centre - Northside",
    "City Centre - Southside",
    "Dalkey",
    "Deansgrange",
    "Donnybrook",
    "Drumcondra",
    "Dundrum",
    "Dun Laoighre",
    "Foxrock",
    "Glenageary",
    "Goatstown",
    "Kilmacud",
    "Kilmainham",
    "Merrion",
    "Milltown",
    "Mount Merrion",
    "Raheny",
    "Ranelagh",
    "Rathfarnam",
    "Rathmines",
    "Ringsend",
    "Sandymount",
    "Stillorgan",
    "Terenure",
    "UCD",
    "Windy Arbour",
]

LOCATION_LIMITS = {
    "Ballsbridge": {"people": 10, "leaders": 1, "sublocations": []},
    "Blackrock": {"people": 10, "leaders": 1, "sublocations": []},
    "Booterstown": {"people": 10, "leaders": 1, "sublocations": []},
    "Bray": {"people": 10, "leaders": 1, "sublocations": []},
    "Cabinteely": {"people": 10, "leaders": 1, "sublocations": []},
    "Clonskeagh": {"people": 10, "leaders": 1, "sublocations": []},
    "Clontarf": {"people": 10, "leaders": 1, "sublocations": []},
    "City Centre - Northside": {"people": 80, "leaders": 1, "sublocations": []},
    "City Centre - Southside": {"people": 80, "leaders": 1, "sublocations": []},
    "Dalkey": {"people": 10, "leaders": 1, "sublocations": []},
    "Deansgrange": {"people": 10, "leaders": 1, "sublocations": []},
    "Donnybrook": {"people": 10, "leaders": 1, "sublocations": []},
    "Drumcondra": {"people": 10, "leaders": 1, "sublocations": []},
    "Dundrum": {"people": 10, "leaders": 1, "sublocations": []},
    "Dun Laoighre": {"people": 10, "leaders": 1, "sublocations": []},
    "Foxrock": {"people": 10, "leaders": 1, "sublocations": []},
    "Glenageary": {"people": 10, "leaders": 1, "sublocations": []},
    "Goatstown": {"people": 10, "leaders": 1, "sublocations": []},
    "Kilmacud": {"people": 10, "leaders": 1, "sublocations": []},
    "Kilmainham": {"people": 10, "leaders": 1, "sublocations": []},
    "Merrion": {"people": 10, "leaders": 1, "sublocations": []},
    "Milltown": {"people": 10, "leaders": 1, "sublocations": []},
    "Mount Merrion": {"people": 10, "leaders": 1, "sublocations": []},
    "Raheny": {"people": 10, "leaders": 1, "sublocations": []},
    "Ranelagh": {"people": 10, "leaders": 1, "sublocations": []},
    "Rathfarnam": {"people": 10, "leaders": 1, "sublocations": []},
    "Rathmines": {"people": 10, "leaders": 1, "sublocations": []},
    "Ringsend": {"people": 10, "leaders": 1, "sublocations": []},
    "Sandymount": {"people": 10, "leaders": 1, "sublocations": []},
    "Stillorgan": {"people": 10, "leaders": 1, "sublocations": []},
    "Terenure": {"people": 10, "leaders": 1, "sublocations": []},
    "UCD": {"people": 10, "leaders": 1, "sublocations": []},
    "Windy Arbour": {"people": 10, "leaders": 1, "sublocations": []},
}

COLUMNS_TO_DROP = [
    "Timestamp",
    "Email\n",
    "Name",
    "Your phone number",
    "Any dietary requirements/allergens for the breakfast eg Halal, Veg, etc.",
    "T-shirt size",
]

DTYPE_DICT = {
    "email": "string",
    "year": "string",
    "signup": "bool",
    "p1": "category",
    "p2": "category",
    "p3": "category",
}

SIGNUP_MAP = {
    "Yes": True,
    "No": False,
    "": False,
}

DF_COLUMNS = list(DTYPE_DICT.keys())
